name: "Continuous Integration"

on:   
  push:
    branches:
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "master"
  pull_request:
    branches:
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "master"

jobs:

  latest:
    name: "Build & Verify"
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - name: PHPUnit Tests
        uses: php-actions/phpunit@master
        with:
          php_extensions: xdebug
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml.dist
          args: --coverage-clover ./coverage.xml
        env:
          XDEBUG_MODE: coverage
      - run: |
          find src -name "*.php" -exec ./bin/metrics annotate ./coverage.xml {} \;
      - run: |
          ./vendor/bin/rector process src
      - run: |
          find tests -name "*.php" -exec ./vendor/bin/phptidy.php replace {} \;
          find src -name "*.php" -exec ./vendor/bin/phptidy.php replace {} \;
      - run: |
          git diff --exit-code src || ( \
            git config user.name github-actions && \
            git config user.email github-actions@github.com && \
            git add src && \
            git commit -m "tidy" && \
            git fetch --unshallow origin ${{ github.head_ref || github.ref_name }} && \
            git push origin HEAD:${{ github.head_ref || github.ref_name }} \
          )

  matrix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - operating-system: 'ubuntu-latest'
            php-version: '8.2'
          - operating-system: 'ubuntu-latest'
            php-version: '8.1'
          - operating-system: 'ubuntu-latest'
            php-version: '8.0'
          - operating-system: 'ubuntu-latest'
            php-version: '7.4'
          - operating-system: 'ubuntu-latest'
            php-version: '7.2'
  
    name: "Matrix: PHP ${{ matrix.php-version }}"
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-version }}
      - run: |
          ./vendor/bin/phpunit -c phpunit.xml.dist \
          --coverage-clover ./coverage.xml

  merge:

    name: "Merge Changes"
    if: github.event_name == 'push'
    needs: [latest,matrix]
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - run: |
          false || ( \
            git config user.name github-actions && \
            git config user.email github-actions@github.com && \
            git fetch --unshallow origin ${{ github.ref_name }} develop && \
            git checkout develop && \
            git merge origin/${{ github.ref_name }} && \
            git push \
          )
