name: "Merge"

on: 
  push:
    branches:
      - "hotfix/*"
      - "release/*"
      - "master"

jobs:

  merge:

    name: "Merge changes"
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - run: |
          false || ( \
            git config user.name github-actions && \
            git config user.email github-actions@github.com && \
            git fetch --unshallow origin ${{ github.ref_name }} develop && \
            git checkout develop && \
            git merge ${{ github.ref_name }} && \
            git add . && \
            git commit -m "merge" --allow-empty && \
            git push \
          )
