name: Github Autorelease

on: 
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
    tags:
      - "v*"

jobs:

  release:
    name: "Create Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false

  